@isTest
private class FL_FlosumServiceTest 
{
    static testMethod void serviceTest() 
    {
        new FL_FlosumService.LogInfo();
        new FL_FlosumService.DebuggingInfo_element();
        new FL_FlosumService.CallOptions_element();
        new FL_FlosumService.DebuggingHeader_element();
        new FL_FlosumService.listBranchesResponse_element();
        new FL_FlosumService.AllowFieldTruncationHeader_element();
        new FL_FlosumService.listBranches_element();
        new FL_FlosumService.checkComponentsWithBranch_element();
        new FL_FlosumService.checkAttachmentsWithBranch_element();
        new FL_FlosumService.checkAttachmentsWithBranchID_element();
        new FL_FlosumService.checkPatchRemoteBranch_element();
        new FL_FlosumService.checkComponentHistoryRemoteBranch_element();
        new FL_FlosumService.checkComponentsWithBranchResponse_element();
        new FL_FlosumService.checkAttachmentsWithBranchResponse_element();
        new FL_FlosumService.checkAttachmentsWithBranchIDResponse_element();
        new FL_FlosumService.checkPatchRemoteBranchResponse_element();
        new FL_FlosumService.checkComponentHistoryRemoteBranchResponse_element();
        new FL_FlosumService.getBranchNameResponse_element();
        new FL_FlosumService.getBranchName_element();
        new FL_FlosumService.checkCrcFromBranchAndRemoteRepository_element();
        new FL_FlosumService.commitToBranchResponse_element();
        new FL_FlosumService.checkCrcFromBranchAndRemoteRepositoryResponse_element();
        new FL_FlosumService.getSupportedMetadataTypesResponse_element();
        new FL_FlosumService.getSupportedMetadataTypes_element();
        new FL_FlosumService.commitToBranch_element();
    }
}